services:
  # Service Base de Données
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartretail
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service Application (API + UI)
  app:
    build: .
    depends_on:
      - db
    environment:
      # L'URL de connexion : on utilise le nom du service 'db' comme hôte
      - DATABASE_URL=postgresql://user:password@db:5432/smartretail
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
      - ./src:/app/src
      - ./data:/app/data
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./mlruns:/mlflow
    # Lancement simultané API + Streamlit
    command: sh -c "uvicorn src.api.app:app --host 0.0.0.0 --port 8000 & streamlit run src/ui/Home.py --server.port 8501 --server.address 0.0.0.0"

  # Service MLflow
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1  # <--- Version stable fixée
    container_name: smartretail-mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri file:///mlflow
      --host 0.0.0.0
      --serve-artifacts
    volumes:
      - ./mlruns:/mlflow

volumes:
  postgres_data: