[tool.poetry]
name = "smartretail"
version = "0.1.0"
description = "AI Powered Kitchen Assistant"
authors = ["Cyril"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

# --- CORE APP ---
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
sqlalchemy = "^2.0.29"
psycopg2-binary = "^2.9.9"
pgvector = "^0.2.5"
requests = "^2.31.0"
python-multipart = "^0.0.9"

# --- UI ---
streamlit = "^1.32.0"

# --- AI & MLOPS ---
# On force Numpy < 2 pour satisfaire MLflow 2.12
numpy = "<2.0.0"

# NLP Frameworks
sentence-transformers = "^2.6.0"
spacy = "^3.7.4"  # <--- AJOUTÉ ICI POUR CORRIGER L'ERREUR

# MLflow 2.12.1 (Version stable Docker)
mlflow = "2.12.1"

# OR-Tools 9.9 (Compatible avec le vieux Protobuf de MLflow)
ortools = "9.9.3963"

# Monitoring de drift
evidently = "^0.4.0"

# Data Science Standard
pandas = "^2.2.0"
scikit-learn = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"